title: GeckoView
email: etoop@mozilla.com
description:
  The privacy focussed WebView you've been looking for.
baseurl: "/geckoview" # the subpath of your site, e.g. /blog
url: "https://mozilla.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: geckoview
github_username:  mozilla
tags: [GeckoView,Gecko,mozilla,android,WebView,web,browser,toolkit,open source,privacy,online,security,mobile]

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs@aa0d8f1d400b051c090b04b3e530c2848afb585c
plugins:
  - jekyll-feed
  - jekyll-seo-tag

search_enabled: true
